yarnPath: .yarn/releases/yarn-3.2.2.cjs
nodeLinker: node-modules

# https://github.com/plouc/nivo/issues/1941
packageExtensions:
  '@nivo/legends@*':
    peerDependencies:
      'd3-scale': '*'
      '@nivo/colors': '*'
