= patient-journey-client

image:https://github.com/fhnw-medical-informatics/patient-journey/actions/workflows/main.yml/badge.svg[]

Web application, based on React, TypeScript & MUI 5.

Bootstrapped via https://github.com/netzwerg/react-you-do-you[react-you-do-you v2]

TIP: Development setup, architecture & available scripts are documented in the respective https://github.com/netzwerg/react-you-do-you/blob/main/README.adoc[README]


== Data Format

All data is loaded from tabular CSV files.
The following sections describe their general structure as well as entity-specific requirements:

=== Patient & Event Data

Each file must start with two header rows: row 1 specifying column names, row 2 specifying <<column-types, column types>>.
Actual data hence spans from row 3 to row n.

----
1 Name    Age
2 string  number
3 Banana  42
...
n Apple   99
----

Depending on the specific entity, each table contains certain mandatory columns and can contain 0..n custom columns.

[[column-types]]
=== Column Types

Column types are used to:

* uniquely *identify* rows/entities
* define *relationships* between entities (e.g. link events to patients)
* *render* values in the UI (e.g. display boolean `true` as checkbox)
* *sort* values (e.g. sort `date` values chronologically rather than alpha-numerically)
* *filter* values (e.g. histograms for `number` vs toggles for `boolean`)

The following types are supported:

`pid`:: string values which uniquely identify patients
`eid`:: string values which uniquely identify events
`string`:: valid https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#string_type[JavaScript string values]
`boolean`:: either `true` or `false`
`number`:: valid numerical values (convertable via unary + operator)
`timestamp`:: milliseconds since epoch (rendered specific to timezone/locale)
`date`:: data values formatted as `dd.MM.yyyy` (rendered as is, *not* timezone/locale specific, thus suitable for birthdays)
`category`:: categorical variable (string or number) that can take on a limited number of possible values

==== Patient Data Example

----
Patient ID,First Name,Last Name,Date Of Birth,Height,Blood Type
pid,string,string,date,number,category
p1,Raphael,Blumenthal,07.12.1929,179,A
p2,Dany,Bär,03.06.1985,181,B
p3,Candice,Schaich,26.02.1991,171,O
p4,Janosch,Schick,11.07.1935,165,AB
p5,Alessio,Weber,30.07.1965,178,A
p6,Kreshnik,Süss,22.02.1971,189,B
p7,Edon,Fisler,06.10.1957,175,B
p8,Vera,Gambacciani,04.12.1952,169,A
p9,Clelia,Jordi,04.08.1927,180,A
----

The first column of type `pid` is used to uniquely identify patients.
If no `pid` column exists, the row index is used as a fallback.

==== Event Data Example

----
Event ID,Patient ID,Timestamp
eid,pid,timestamp
e1,p1,1645453113884
e2,p1,1645454113885
e3,p2,1645455113886
----

The first column of type `eid` is used to uniquely identify events.
If no `eid` column exists, the row index is used as a fallback.

The first column of type `pid` is used to link events to patients.

=== Similarities Matrix (Optional)

Patient similarities are defined as a CSV matrix (without headers):

----
1,0.2,0.3
0.2,1,0.4
0.3,0.4,1
----

Values can be any valid numerical value (convertable via unary + operator).

[IMPORTANT]
Columns and rows need to be sorted in the same order as the respective patient data file (pid).

[TIP]
Rows define _index_ patients, while columns define _other_ patients (only relevant if matrix it not symmetrical).

== Deployment

To deploy the application, follow these steps:

1. Connect to the FHNW network via the FHNW VPN
2. Run `yarn deploy`
3. Follow the instructions to deploy the application
4. Access the application via https://pub.ima.lifesciences.fhnw.ch/pj/app/[https://pub.ima.lifesciences.fhnw.ch/pj/app/]

&copy; FHNW Medical Decision Support Systems Group 2022 – link:LICENSE[MIT License]
