= patient-journey-client

image:https://github.com/fhnw-medical-informatics/patient-journey/actions/workflows/main.yml/badge.svg[]

Web application, based on React, TypeScript & MUI 5.

Bootstrapped via https://github.com/netzwerg/react-you-do-you[react-you-do-you v2]

TIP: Development setup, architecture & available scripts are documented in the respective https://github.com/netzwerg/react-you-do-you/blob/main/README.adoc[README]


== Data Format

All data is loaded from tabular CSV files.
The following sections describe their general structure as well as entity-specific requirements:

=== General Structure

Each file must start with two header rows: row 1 specifying column names, row 2 specifying <<column-types, column types>>.
Actual data hence spans from row 3 to row n.

----
1 Name    Age
2 string  number
3 Banana  42
...
n Apple   99
----

Depending on the specific entity, each table contains certain mandatory columns and can contain 0..n custom columns.

[[column-types]]
=== Column Types

Column types are used to:

* uniquely *identify* rows/entities
* define *relationships* between entities (e.g. link events to patients)
* *render* values in the UI (e.g. display boolean `true` as checkbox)
* *sort* values (e.g. sort `date` values chronologically rather than alpha-numerically)
* *filter* values (e.g. histograms for `number` vs toggles for `boolean`)

The following types are supported:

`pid`:: string values which uniquely identify patients
`eid`:: string values which uniquely identify events
`string`:: valid https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#string_type[JavaScript string values]
`boolean`:: either `true` or `false`
`number`:: valid numerical values (convertable via unary + operator)
`timestamp`:: milliseconds since epoch (rendered specific to timezone/locale)
`date`:: data values formatted as `dd.MM.yyyy` (rendered as is, *not* timezone/locale specific, thus suitable for birthdays)

=== Specific Structure
==== Patient Data

Demo example: link:public/data/mock-patients.csv[mock-patients.csv]

Mandatory column types:

* `pid`

==== Event Data

Demo example: link:public/data/mock-events.csv[mock-events.csv]

Mandatory column types:

* `pid`
* `eid`


&copy; FHNW Medical Decision Support Systems Group 2022 – link:LICENSE[MIT License]
