= patient-journey-client

image:https://github.com/fhnw-medical-informatics/patient-journey/actions/workflows/main.yml/badge.svg[]

Web application, based on React, TypeScript & MUI 5.

Bootstrapped via https://github.com/netzwerg/react-you-do-you[react-you-do-you v2]

TIP: Development setup, architecture & available scripts are documented in the respective https://github.com/netzwerg/react-you-do-you/blob/main/README.adoc[README]


== Data Format

All data is loaded from tabular CSV files.
The following sections describe their general structure as well as entity-specific requirements:

=== General Structure

Each file must start with two header rows: row 1 specifying column names, row 2 specifying <<column-types, column types>>.
Actual data hence spans from row 3 to row n.

----
1 Name    Age
2 string  number
3 Banana  42
...
n Apple   99
----

Depending on the specific entity, each table contains certain mandatory columns and can contain 0..n custom columns.

[[column-types]]
=== Column Types

Column types are used to:

* uniquely *identify* rows/entities
* define *relationships* between entities (e.g. link events to patients)
* *render* values in the UI (e.g. display boolean `true` as checkbox)
* *sort* values (e.g. sort `date` values chronologically rather than alpha-numerically)
* *filter* values (e.g. histograms for `number` vs toggles for `boolean`)

The following types are supported:

`pid`:: string values which uniquely identify patients
`eid`:: string values which uniquely identify events
`string`:: valid https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#string_type[JavaScript string values]
`boolean`:: either `true` or `false`
`number`:: valid numerical values (convertable via unary + operator)
`timestamp`:: milliseconds since epoch (rendered specific to timezone/locale)
`date`:: data values formatted as `dd.MM.yyyy` (rendered as is, *not* timezone/locale specific, thus suitable for birthdays)
`quality`:: qualitative variable (string or number) that can take on a limited number of possible values

=== Specific Structure
==== Patient Data

Example:

----
Patient ID,First Name,Last Name,Date Of Birth,Height,Blood Type
pid,string,string,date,number,quality
1,Raphael,Blumenthal,07.12.1929,179,A
2,Dany,Bär,03.06.1985,181,B
3,Candice,Schaich,26.02.1991,171,O
4,Janosch,Schick,11.07.1935,165,AB
5,Alessio,Weber,30.07.1965,178,A
6,Kreshnik,Süss,22.02.1971,189,B
7,Edon,Fisler,06.10.1957,175,B
8,Vera,Gambacciani,04.12.1952,169,A
9,Clelia,Jordi,04.08.1927,180,A
----

The first column of type `pid` is used to uniquely identify patients.
If no `pid` column exists, the row index is used as a fallback.

==== Event Data

----
Event ID,Patient ID,Timestamp
eid,pid,timestamp
1,1,1645453113884
2,1,1645454113885
3,2,1645455113886
----

The first column of type `eid` is used to uniquely identify events.
If no `eid` column exists, the row index is used as a fallback.

The first column of type `pid` is used to link events to patients.

&copy; FHNW Medical Decision Support Systems Group 2022 – link:LICENSE[MIT License]
